version: '3.8'
services:
  #######################################################
  #  Postgress
  #######################################################
    
  db:
   container_name: postgres
   image: postgres:15-alpine
   ports:
    - 5432:5432
   environment:
    - POSTGRES_USER=postgress
    - POSTGRES_PASSWORD=postgress